export const theme = {
    colors: {
        utaPrimary: "#8a1538",
        utaSecondary: "#630f28",
        utaAccent: "#ffd700",
        primary: "#8a1538",
        primaryDark: "#5f1027",
        primaryHover: "#6a102c",
        primaryLight: "rgba(138, 21, 56, 0.12)",
        primaryLighter: "rgba(138, 21, 56, 0.06)",
        bgPrimary: "#ffffff",
        bgSecondary: "#f5f7fa",
        bgTertiary: "#edf1f7",
        bgElevated: "#ffffff",
        bgCard: "#ffffff",
        textPrimary: "#1a1f2e",
        textSecondary: "#6b7280",
        textTertiary: "#9ca3af",
        textInverse: "#ffffff",
        borderPrimary: "#e8ecf2",
        borderSecondary: "#d1d5db",
        borderLight: "#f0f2f7",
        success: "#10b981",
        successLight: "rgba(16, 185, 129, 0.1)",
        warning: "#f59e0b",
        warningLight: "rgba(245, 158, 11, 0.1)",
        error: "#ef4444",
        errorLight: "rgba(239, 68, 68, 0.1)",
        tabBarBg: "#ffffff",
        tabBarBorder: "#f0f2f5",
    },
    gradients: {
        primary: ["#8a1538", "#5f1027"] as const,
        header: ["#8a1538", "#6e0e2d"] as const,
        hero: ["rgba(138, 21, 56, 0.96)", "rgba(80, 10, 30, 0.98)"] as const,
        card: ["#f8f9fc", "#eef1f7"] as const,
        surface: ["#ffffff", "#f9fafb"] as const,
    },
    shadow: {
        xs: {
            shadowColor: "#000",
            shadowOpacity: 0.05,
            shadowRadius: 4,
            shadowOffset: { width: 0, height: 1 },
            elevation: 1,
        },
        sm: {
            shadowColor: "#000",
            shadowOpacity: 0.08,
            shadowRadius: 10,
            shadowOffset: { width: 0, height: 3 },
            elevation: 3,
        },
        md: {
            shadowColor: "#000",
            shadowOpacity: 0.12,
            shadowRadius: 18,
            shadowOffset: { width: 0, height: 6 },
            elevation: 6,
        },
        lg: {
            shadowColor: "#000",
            shadowOpacity: 0.18,
            shadowRadius: 28,
            shadowOffset: { width: 0, height: 10 },
            elevation: 10,
        },
        primary: {
            shadowColor: "#8a1538",
            shadowOpacity: 0.30,
            shadowRadius: 22,
            shadowOffset: { width: 0, height: 8 },
            elevation: 8,
        },
        tab: {
            shadowColor: "#000",
            shadowOpacity: 0.10,
            shadowRadius: 20,
            shadowOffset: { width: 0, height: -4 },
            elevation: 12,
        },
    },
    radius: {
        xs: 6,
        sm: 12,
        md: 18,
        lg: 24,
        xl: 32,
        full: 999,
    },
    spacing: {
        xs: 4,
        sm: 10,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
    },
    font: {
        title: "System",
        body: "System",
    },
    sizes: {
        inputHeight: 52,
        buttonHeight: 52,
        tabBarHeight: 68,
        headerHeight: 60,
        iconBtn: 44,
    },
};
